export const data =[
    {
        "id": "1830kl02_p",
        "name": "Titan Men's Maritime Pro Lateen Sail Chronograph Watch",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwdb89d3af/images/Titan/Catalog/1830KL02_1.jpg",
        "price": 13450,
        "listedPrice": 16815,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "1688km06_p",
        "name": "Titan Regalia Premium Blue Dial Quartz Multifunction Stainless Steel Strap watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwef1a0f86/images/Titan/Catalog/1688KM06_1.jpg",
        "price": 11995,
        "listedPrice": 14995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "90175kd03_p",
        "name": "Titan Ceramic Fusion Skeleton Automatic Rich Black Dial Steel & Ceramic Strap Watch For Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwee4d2ee0/images/Titan/Catalog/90175KD03_1.jpg",
        "price": 27495,
        "listedPrice": 27495,
        "gender": "gents",
        "isDiscounted": false,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.2
    }  ,
    {
        "id": "1733kl03_p",
        "name": "Titan Quartz Multifunction Blue Dial Leather Strap Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw5460fdbb/images/Titan/Catalog/1733KL03_1.jpg",
        "price": 4795,
        "listedPrice": 5995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    }
    ,
    {
        "id": "90127km02_p",
        "name": "Titan Opulent Blue Dial Quartz Multifunction Stainless Steel Strap watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwbb79d68a/images/Titan/Catalog/90127KM02_1.jpg",
        "price": 7710,
        "listedPrice": 9635,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "90175kd02_p",
        "name": "Titan Ceramic Fusion Skeleton Automatic Rich Blue Dial Steel & Ceramic Strap Watch For Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwd9e94791/images/Titan/Catalog/90175KD02_1.jpg",
        "price": 26495,
        "listedPrice": 26495,
        "gender": "gents",
        "isDiscounted": false,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4
    },
    
    {
        "id": "1802nl02_p",
        "name": "Titan Workwear Green Dial Analog Leather Strap Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwe485817b/images/Titan/Catalog/1802NL02_1.jpg",
        "price": 2700,
        "listedPrice": 3375,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "2608qm02_p",
        "name": "Raga Women's Allure: Brown Dial with designer Metal Strap Watch",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw77995370/images/Titan/Catalog/2608QM02_1.jpg",
        "price": 4795,
        "listedPrice": 5995,
        "gender": "ladies",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.5    
    },
{
    "id": "2656wl01_p",
    "name": "Titan Women's Lagan Chic: Studded Brown Dial watch with & Elegant Hands",
    "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwf87788bb/images/Titan/Catalog/2656WL01_1.jpg",
    "price": 1795,
    "listedPrice": 1995,
    "gender": "ladies",
    "isDiscounted": true,
    "quantity":1,
  "developer": "tenacious_developer",
   "rating": 4.1
},
    {
        "id": "2143rl14_g",
        "name": "Titan Edge Ceramic Quartz in Midnight Gold with Diamonds and Black Dial Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw8fc37a35/images/Titan/Catalog/1696KC02_1.jpg",
        "price": 39995,
        "listedPrice": 39995,
        "gender": "gents",
        "isDiscounted": false,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.2
    },
    {
        "id": "1696nc12_p",
        "name": "Titan Edge Ceramic Quartz in Glossy Black with Diamonds and Black Dial Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw0d9eb436/images/Titan/Catalog/1696NC12_1.jpg",
        "price": 38995,
        "listedPrice": 38995,
        "gender": "gents",
        "isDiscounted": false,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.2
    } ,
    {
        "id": "1696qc09_p",
        "name": "Titan Edge Ceramic Quartz in Atlantic Blue Dial with Diamonds Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw8fac1b4f/images/Titan/Catalog/1696QC09_1.jpg",
        "price": 38995,
        "listedPrice": 38995,
        "gender": "gents",
        "isDiscounted": false,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4
    },
{
    "id": "1806nm01_p",
    "name": "Titan Men's Timeless Style Watch: Refined Black Dial and Metal Strap",
    "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwcfb00132/images/Titan/Catalog/1806NM01_1.jpg",
    "price": 3195,
    "listedPrice": 3995,
    "gender": "gents",
    "isDiscounted": true,
    "quantity":1,
  "developer": "tenacious_developer",
   "rating":4.7},
{
    "id": "90166ap02_p",
    "name": "Titan Traveller with 4.52 cm AMOLED Display, BT Calling, India's First FitVerse Smartwatch with Blue Leather Strap",
    "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwb85e3c38/images/Titan/Catalog/90166AP02_1.jpg",
    "price": 12995,
    "listedPrice": 18995,
    "gender": "gents",
    "isDiscounted": true,
    "quantity":1,
  "developer": "tenacious_developer",
   "rating": 4.3} ,
    {
    "id": "90188ap01_p",
    "name": "Titan Smart Watch with 4.97 CM Super AMOLED Display | 410 x 502 Pixel Resolution | AI Voice Assistant | Multiple Menu Styles",
    "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw61458d43/images/Titan/Catalog/90188AP01_1.jpg",
    "price": 4995,
    "listedPrice": 11995,
    "gender": "gents",
    "isDiscounted": true,
    "quantity":1,
  "developer": "tenacious_developer",
   "rating": 4.3},  

    
   {
       "id": "90166ap03_p",
        "name": "Titan Traveller with 4.52 cm AMOLED Display, BT Calling, India's First FitVerse Smartwatch with Brown Leather Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw5c078218/images/Titan/Catalog/90166AP03_1.jpg",
        "price": 12995,
        "listedPrice": 18995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "90166ap04_p",
        "name": "Titan Traveller with 4.52 cm AMOLED Display, BT Calling, India's First FitVerse Smartwatch with Wine Red Leather Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw0bf22148/images/Titan/Catalog/90166AP04_1.jpg",
        "price": 12995,
        "listedPrice": 18995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.1    
    }  ,
    {
        "id": "90137ap02_p",
        "name": "Titan Smart Touch Screen Smart WatchBlue Silicone Strap watch for Unisex",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw425bdc0f/images/Titan/Catalog/90137AP02_1.jpg",
        "price": 8995,
        "listedPrice": 11995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.6    
    },
    {
        "id": "90165ap02_p",
        "name": "Titan Talk S Blue Dial Smart Silicone Strap watch for Unisex",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw382a5ace/images/Titan/Catalog/90165AP02_1.jpg",
        "price": 8995,
        "listedPrice": 12995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "90184al03_p",
        "name": "Titan Mirage with 4.97 cm AMOLED Display and AOD, Functional Crown, BT Calling Smartwatch with Pink Leather Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw0f1a5fab/images/Titan/Catalog/90184AL03_1.jpg",
        "price": 8995,
        "listedPrice": 11995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.7    
    },
    {
        "id": "90188ap03_p",
        "name": "Titan Smart Watch with 4.97 CM Super AMOLED Display | 410 x 502 Pixel Resolution | AI Voice Assistant | Multiple Menu Styles",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwcf9305b4/images/Titan/Catalog/90188AP03_1.jpg",
        "price": 4995,
        "listedPrice": 11995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.9    
    },
    {
        "id": "90197al01_p",
        "name": "Titan Crest with 3.63 cm AMOLED Display with AOD, Functional Crown, BT Calling Smartwatch with Black Leather Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw00c986b8/images/Titan/Catalog/90197AL01_1.jpg",
        "price": 6995,
        "listedPrice": 12995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "90206ap03_p",
        "name": "Titan Celestor Advanced GPS & Barometer 3.6 CM AMOLED Display with AOD, Pizoelectric Functional Crown Moonlight Edition",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwf02861e2/images/Titan/Catalog/90206AP03_1.jpg",
        "price": 9995,
        "listedPrice": 9995,
        "gender": "gents",
        "isDiscounted": false,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.2
    },
    {
        "id": "90197al02_p",
        "name": "Titan Crest with 3.63 cm AMOLED Display with AOD, Functional Crown, BT Calling Smartwatch with Brown Leather Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwb2baadf5/images/Titan/Catalog/90197AL02_1.jpg",
        "price": 6995,
        "listedPrice": 12995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "90197am01_p",
        "name": "Titan Crest with 3.63 cm AMOLED Display with AOD, Functional Crown, BT Calling Smartwatch with Black Mesh Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwd07d43e9/images/Titan/Catalog/90197AM01_1.jpg",
        "price": 7995,
        "listedPrice": 13995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.4    
    },
    {
        "id": "90196am01_p",
        "name": "Titan Zeal with 4.69 cm AMOLED Display with AOD, Functional Crown, BT Calling, Smartwatch with Black Mesh Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwf1f0c917/images/Titan/Catalog/90196AM01_1.jpg",
        "price": 9995,
        "listedPrice": 13995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.1   
    }, 
    {
        "id": "90197ap01k_p",
        "name": "Titan Crest with 3.63 cm AMOLED Display with AOD, Functional Crown, BT Calling, Premium Smartwatch with Black Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw3b51417e/images/Titan/Catalog/90197AP01K_1.jpg",
        "price": 5995,
        "listedPrice": 11995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
        "id": "90184am01_p",
        "name": "Titan Mirage with 4.97 cm AMOLED Display and AOD, Functional Crown, BT Calling Smartwatch with Black Metal Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwa459bb41/images/Titan/Catalog/90184AM01_1.jpg",
        "price": 9995,
        "listedPrice": 12995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.8    
    },
    {
        "id": "90197ap01_p",
        "name": "Titan Crest with 3.63 cm AMOLED Display with AOD, Functional Crown, BT Calling, Premium Smartwatch with Black Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw0b497d8a/images/Titan/Catalog/90197AP01_1.jpg",
        "price": 5995,
        "listedPrice": 11995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.4   
    },
    {
        "id": "90196al01_p",
        "name": "Titan Zeal with 4.69 cm AMOLED Display with AOD, Functional Crown, BT Calling, Smartwatch with Black Leather Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw3c10e1bb/images/Titan/Catalog/90196AL01_1.jpg",
        "price": 8995,
        "listedPrice": 12995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.1    
    },
   {
    "id": "1639sm02_p",
    "name": "Titan Men's Elegance Watch: Black Dial with Sleek Link Strap",
    "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw5dea78ac/images/Titan/Catalog/1639SM02_1.jpg",
    "price": 1795,
    "listedPrice": 1995,
    "gender": "gents",
    "isDiscounted": true,
    "quantity":1,
  "developer": "tenacious_developer",
   "rating":4.9
},
     {
        "id": "1828km02_p",
        "name": "Titan Grandmaster Brown Dial Analog Stainless Steel Strap Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw4743ffe5/images/Titan/Catalog/1828KM02_1.jpg",
        "price": 8715,
        "listedPrice": 10045,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    },
    {
    "id": "90086km05_p",
    "name": "Titan Octane Black Dial Chronograph Watch for Men",
    "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwc07c110a/images/Titan/Catalog/90086KM05_1.jpg",
    "price": 9410,
    "listedPrice": 11765,
    "gender": "gents",
    "isDiscounted": true,
    "quantity":1,
  "developer": "tenacious_developer",
   "rating":4.4
},

{
    "id": "1849ym01_p",
    "name": "Titan Black and Gold Quartz Analog with Date Silver Dial Stainless Steel Strap Watch for Men",
    "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dwe1a94e04/images/Titan/Catalog/1849YM01_1.jpg",
    "price": 5210,
    "listedPrice": 7445,
    "gender": "gents",
    "isDiscounted": true,
    "quantity":1,
  "developer": "tenacious_developer",
   "rating":4.6},
     {
        "id": "1713bm02_p",
        "name": "Titan Men's Multifunction Karishma: Two-Tone Steel Elegance Watch",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw3e10e985/images/Titan/Catalog/1713BM02_1.jpg",
        "price": 2870,
        "listedPrice": 3585,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.4    
    },
    {
        "id": "2656wm01_p",
        "name": "Titan Women's Lagan Watch: Rose Gold Accents & Refined Elegance",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw6c9df22a/images/Titan/Catalog/2656WM01_1.jpg",
        "price": 2550,
        "listedPrice": 2835,
        "gender": "ladies",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.5    
    },
    {
        "id": "1805qm01_p",
        "name": "Titan Neo Splash Blue Dial Quartz Multifunction Stainless Steel Strap watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw1888ad40/images/Titan/Catalog/1805QM01_1.jpg",
        "price": 6395,
        "listedPrice": 7995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    } , 
    {
        "id": "1805qm04_p",
        "name": "Titan Neo Splash Quartz Multifunction Black Dial Stainless Steel Strap Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw0814ec34/images/Titan/Catalog/1805QM04_1.jpg",
        "price": 5875,
        "listedPrice": 7345,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    } ,
    {
        "id": "1806nl02_p",
        "name": "Titan Men's Timeless Style Watch: Refined Gold Dial and Leather Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw758a93e3/images/Titan/Catalog/1806NL02_1.jpg",
        "price": 2795,
        "listedPrice": 3995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.3    
    } ,
    
    {
        "id": "1824bm03_p",
        "name": "Titan Men's Trendsetter Watch: Chic Blue Dial & Two-Tone Strap",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw9c842df9/images/Titan/Catalog/1824BM03_1.jpg",
        "price": 3195,
        "listedPrice": 3995,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.1    
    },
    {
        "id": "sp70028nm01w_p",
        "name": "Sonata Poze Quartz Analog Black Dial Metal Strap Watch for Men",
        "imageUrl": "https://www.titan.co.in/on/demandware.static/-/Sites-titan-master-catalog/default/dw569da3aa/images/Sonata/Catalog/SP70028NM01W_1.jpg",
        "price": 1195,
        "listedPrice": 1725,
        "gender": "gents",
        "isDiscounted": true,
        "quantity":1,
        "developer": "tenacious_developer",
        "rating": 4.2    
    }]